# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6807ef97c37d5f53131c80e9e963ff70810ebba55f3148ca42f78b3f304300b82f09800fa0d9e20514638317931a37bee15c0e417da8b6af0ffb091a717e8ae6
  google:
    key: <%= ENV["GOOGLE_CLIENT_ID"] %>
    secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
test:
  secret_key_base: dc619be0d083d85778780595f99d06dfffb435e4fdc04616cdd24093da33bafbc271afd5bf863da1758f7074f20ed877b2e06a68dd73e9d035132c69002bc2b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
